import { DocType } from "@prisma/client";
import { prisma } from "@/server/db/prisma";
import { writeAuditEvent } from "@/server/audit/events";
import { evaluateDocumentQualityGate } from "@/server/quality/documentQualityGate";
import { persistGeneratedPayload } from "@/server/verification/persistence";
import { buildPipelineArtifacts } from "@/server/pipeline/generator";

const pipelineOrder: DocType[] = [DocType.URS, DocType.RID, DocType.IOQ, DocType.OQ, DocType.TRACEABILITY];

type PipelineResultDoc = {
  docType: DocType;
  documentId: string;
  version: number;
  hash: string;
};

const toSelectedDocTypes = (selected: string[] | undefined) => {
  if (!selected || selected.length === 0) return pipelineOrder;
  const valid = selected.filter((item): item is DocType => pipelineOrder.includes(item as DocType));
  return valid.length > 0 ? valid : pipelineOrder;
};

export const runGenerationPipeline = async (params: {
  organizationId: string;
  userId: string;
  machineId: string;
  intendedUse: string;
  selectedDocTypes?: string[];
  request?: Request;
}) => {
  const selectedDocTypes = toSelectedDocTypes(params.selectedDocTypes);
  const machine = await prisma.machine.findFirst({
    where: { id: params.machineId, organizationId: params.organizationId }
  });
  if (!machine) {
    throw new Error("Machine not found.");
  }

  const user = await prisma.user.findUnique({
    where: { id: params.userId },
    select: { email: true }
  });
  const facts = await prisma.equipmentFact.findMany({
    where: { organizationId: params.organizationId, machineId: machine.id },
    orderBy: [{ factType: "asc" }, { key: "asc" }, { createdAt: "asc" }]
  });
  const generatedAt = new Date().toISOString();
  const artifacts = buildPipelineArtifacts({
    systemName: machine.name,
    equipmentId: machine.modelNumber,
    generatedBy: user?.email ?? params.userId,
    generatedAt,
    intendedUse: params.intendedUse.trim(),
    facts: facts.map((fact) => ({
      factType: fact.factType,
      key: fact.key,
      value: fact.value,
      units: fact.units,
      sourceRef: fact.sourceRef
    }))
  });

  const docOutputs: PipelineResultDoc[] = [];
  const payloadByType: Record<DocType, unknown> = {
    [DocType.URS]: artifacts.ursPayload,
    [DocType.RID]: artifacts.raPayload,
    [DocType.IOQ]: artifacts.ioqPayload,
    [DocType.OQ]: artifacts.oqPayload,
    [DocType.TRACEABILITY]: artifacts.tmPayload
  } as Record<DocType, unknown>;

  let ursDocId = "";
  let raDocId = "";
  let ioqDocId = "";
  let oqDocId = "";

  for (const docType of pipelineOrder) {
    const persisted = await persistGeneratedPayload({
      organizationId: params.organizationId,
      userId: params.userId,
      machineId: machine.id,
      docType,
      title: `${docType} for ${machine.name}`,
      stage: "PRE_EXECUTION",
      payload: payloadByType[docType],
      citations: {
        schema:
          docType === DocType.URS ? "urs.v1" : docType === DocType.RID ? "ra.v1" : docType === DocType.IOQ ? "ioq.v1" : docType === DocType.OQ ? "oq.v1" : "tm.v1",
        machineId: machine.id,
        intendedUse: params.intendedUse,
        dependsOn: {
          ursDocId: ursDocId || null,
          raDocId: raDocId || null,
          ioqDocId: ioqDocId || null,
          oqDocId: oqDocId || null
        }
      },
      changeComment: `${docType} generated by pipeline`
    });

    if (docType === DocType.URS) ursDocId = persisted.document.id;
    if (docType === DocType.RID) raDocId = persisted.document.id;
    if (docType === DocType.IOQ) ioqDocId = persisted.document.id;
    if (docType === DocType.OQ) oqDocId = persisted.document.id;

    docOutputs.push({
      docType,
      documentId: persisted.document.id,
      version: persisted.version,
      hash: persisted.hash
    });

    await writeAuditEvent({
      organizationId: params.organizationId,
      actorUserId: params.userId,
      action: `${docType.toLowerCase()}.pipeline.generate`,
      entityType: "GeneratedDocument",
      entityId: persisted.document.id,
      details: { machineId: machine.id, version: persisted.version, hash: persisted.hash },
      request: params.request
    });
  }

  const traceabilityDoc = docOutputs.find((doc) => doc.docType === DocType.TRACEABILITY);
  if (traceabilityDoc) {
    const tracePayload = artifacts.tmPayload;
    await prisma.traceabilityLink.createMany({
      data: tracePayload.mappings.map((mapping) => ({
        organizationId: params.organizationId,
        generatedDocumentId: traceabilityDoc.documentId,
        requirementId: mapping.req_id,
        riskControlId: mapping.risk_ids[0] ?? "RISK-UNMAPPED",
        testCaseId: mapping.test_ids[0] ?? "TEST-UNMAPPED",
        citationSourceId: null,
        citationPage: null
      }))
    });
  }

  const docsForGate = pipelineOrder.map((docType) => ({
    id: docOutputs.find((item) => item.docType === docType)?.documentId ?? "",
    docType,
    currentContent: JSON.stringify(payloadByType[docType], null, 2)
  }));
  const traceLinks = artifacts.tmPayload.mappings.flatMap((mapping) =>
    mapping.risk_ids.flatMap((riskId) =>
      mapping.test_ids.map((testId) => ({
        requirementId: mapping.req_id,
        riskControlId: riskId,
        testCaseId: testId
      }))
    )
  );

  const qualityResults = selectedDocTypes.map((docType) =>
    evaluateDocumentQualityGate({
      targetDocumentId: docOutputs.find((item) => item.docType === docType)?.documentId ?? "",
      documents: docsForGate,
      traceLinks
    })
  );
  const qualityIssues = qualityResults.flatMap((result) => result.issues);
  const readyForExport = qualityIssues.length === 0;

  const latestJob =
    (await prisma.generationJob.findFirst({
      where: { organizationId: params.organizationId, machineId: machine.id },
      orderBy: { createdAt: "desc" }
    })) ?? { id: "unknown" };

  await writeAuditEvent({
    organizationId: params.organizationId,
    actorUserId: params.userId,
    action: readyForExport ? "pipeline.generate.completed" : "pipeline.generate.failed_quality_gate",
    entityType: "GenerationJob",
    entityId: latestJob.id,
    details: {
      machineId: machine.id,
      selectedDocTypes,
      readyForExport,
      issueCount: qualityIssues.length
    },
    request: params.request
  });

  return {
    jobId: latestJob.id,
    readyForExport,
    qualityIssues,
    documents: docOutputs.filter((doc) => selectedDocTypes.includes(doc.docType))
  };
};
